### ISSUE TITLE
Integration not available in the integrations UI

### ISSUE THREAD

**Issue by grisu911** [tahvane1/jablotron80#1]
Hi Erkka,

I tryed to use your intergration.
The jablotron is connected via /dev/hidraw0 with a JA-82T

How does the integration work in the ui? Should I find it here?
![Integration UI](https://user-images.githubusercontent.com/46991275/103489526-67f01880-4e15-11eb-9988-f1cc9f90920f.JPG)
If yes than it is not shown.

Or did I misunderstand you?
Can I config the integration any other way?

**Comment by JohnnyM84** [comment]
You need to install it manualy in custom components or with hacs

**Comment by elenril2** [comment]
I have the same problem. I've installed integration via HACS and can't add it in configuration UI. Is there any option to add it from configuration.yaml?
