### ISSUE TITLE
Get unknown timestamp event when the alarm is armed and trying to disarm with the fob

### ISSUE THREAD

**Issue by mazzy89** [tahvane1/jablotron80#10]
```sh
Logger: custom_components.jablotron80
Source: custom_components/jablotron80/jablotron.py:1454
Integration: Jablotron 80 (documentation, issues)
First occurred: 6:50:21 PM (2 occurrences)
Last logged: 6:50:27 PM

Unknown timestamp event data=e3 19 05 18 53 44 3e 60 ff

```

**Comment by tahvane1** [comment]
Could you check from from O-link (events or something like that) what happened at that timestamp? 19 (day), 05 (month),18 (hour), 53 (minutes) , 44 (seconds)

**Comment by mazzy89** [comment]
I will check and I will post the result

**Comment by mazzy89** [comment]
<img width="688" alt="Screenshot 2021-05-19 at 22 52 06" src="https://user-images.githubusercontent.com/5463218/118882842-e2b55e00-b8f4-11eb-8930-82c792e0f322.png">

These are the actions executed in that timeframe

**Comment by mattsaxon** [comment]
So since there are 2 occurences and set and unset are already handled, I suggest this is the ARC message.

**Comment by mattsaxon** [comment]
Fixed in PR #32

**Comment by mattsaxon** [comment]
I will leave open until a new release is cut with this PR in it so @mazzy89 can verify.

**Comment by tahvane1** [comment]
New version was released

**Comment by mattsaxon** [comment]
@tahvane1 appreciated. @mazzy89 can you test and we can close.

**Comment by mattsaxon** [comment]
Closing due to lack of response, we can reopen if feedback received

**Comment by mazzy89** [comment]
thanks. at the moment the issue disapperead.
