### ISSUE TITLE
Error adding integration

### ISSUE THREAD

**Issue by Lirik-JuKi** [tahvane1/jablotron80#109]
Hello,
can not add the integration.
![Capture](https://user-images.githubusercontent.com/97107705/158054076-a6201bcb-3ab2-4b83-8a83-e0f522780d99.PNG)

`This error originated from a custom integration.

Logger: custom_components.jablotron80
Source: custom_components/jablotron80/jablotron.py:1726
Integration: jablotron80 (documentation, issues)
First occurred: 11:41:37 (2 occurrences)
Last logged: 11:49:40

Tampering alarm, 5:device_5, 11:41 Sun 13 Mar
Tampering alarm, 5:device_wired_5, 11:49 Sun 13 Mar`
![Capture2](https://user-images.githubusercontent.com/97107705/158054132-e51286d5-2e3a-40be-98a2-23a5c5421e03.PNG)

**Comment by mattsaxon** [comment]
The above log doesn't look like its is the full log and the times don't match, i.e. the log is from 11:35 and the errors from 11:41-11:49.

The tampering issues should not cause any problem with adding the integration, however it wouldn't be a bad idea to remove them to clean the logs up!

Please can you supply a log from during the adding of the integration and i will investigate.

**Comment by Lirik-JuKi** [comment]
I was removed all jablotron integration, after install as new.
same result.
![Capture](https://user-images.githubusercontent.com/97107705/158056516-814e17e6-9368-4bbb-8128-bf4b6ce05a90.PNG)
![Capture2](https://user-images.githubusercontent.com/97107705/158056518-1b53cdb3-9148-47be-828d-81c358f74d23.PNG)
[Jablotron log.txt](https://github.com/tahvane1/jablotron80/files/8239382/Jablotron.log.txt)

**Comment by mattsaxon** [comment]
ok, thanks for log, I can see an issue, but its not obvious what it is. Have you used the integration before successfully? If so, can I ask you to try with a previous release and tell me if it is this new release that has the issue? Release 0.14 is the one before I made any changes, so that would be a good one to test.

**Comment by Lirik-JuKi** [comment]
This is my first time using the integration. I tried version 0.14, everything is fine there. Integration added.

**Comment by mattsaxon** [comment]
Ok, thanks, I will retest setup with new version, but you should be able to upgrade to latest one now the install is done.

**Comment by mattsaxon** [comment]
Resolved in release 0.25

**Comment by mattsaxon** [comment]
Closing due to lack of response. Reopen if recurrence
