### ISSUE TITLE
Can´t find Jablotorn80 in HACS

### ISSUE THREAD

**Issue by Okrim1974** [tahvane1/jablotron80#13]
I´m confused. I can´t find Jablotron80 in Hacs. It seems that this integration doesn´t exists.

**Comment by mattsaxon** [comment]
You need to add this repository as a custom repository

**Comment by Okrim1974** [comment]
Thanks for the hint. Unfortunately, I'm still an absolute beginner. How do I add the custom repository? Is there a guide?

**Comment by mattsaxon** [comment]
https://hacs.xyz/docs/faq/custom_repositories
