### ISSUE TITLE
After update to HA 2022.06 I get the following "WARNING MESSAGE" 

### ISSUE THREAD

**Issue by blavak68** [tahvane1/jablotron80#134]
Logger: homeassistant.helpers.frame
Source: helpers/frame.py:103
First occurred: 23:39:27 (2 occurrences)
Last logged: 23:39:27

Detected integration that uses deprecated `async_get_registry` to access device registry, use async_get instead. Please report issue to the custom component author for jablotron80 using this method at custom_components/jablotron80/__init__.py, line 39: device_registry = await dr.async_get_registry(hass)

**Comment by blavak68** [comment]
change code on line 39
```
remove
device_registry = await dr.async_get_registry(hass)
new
device_registry = dr.async_get(hass)
```

**Comment by tahvane1** [comment]
This has been changed now. Thank you for reporting.
