### ISSUE TITLE
Any chance to run this on Synology DSM 7?

### ISSUE THREAD

**Issue by raducotescu** [tahvane1/jablotron80#137]
Synology DSM 7 doesn't provide `hidraw` as a kernel module. Is there any other option to run this integration on Synology? For the record, I'm running the HA Core Container.

**Comment by mattsaxon** [comment]
Use a remote serial adapter as described in the readme

**Comment by raducotescu** [comment]
Thanks for jumping in, @mattsaxon! Do you have an "Explain Like I'm Five" guide? Do I need all those three components? I'd like to avoid messing with the alarm's circuit board if possible. 😳

**Comment by mattsaxon** [comment]
No messing needed they plug into your existing ja82t if I recall correctly. There's a picture of the setup on the page isn't there?

**Comment by raducotescu** [comment]
I don't see any picture in the repo with this hardware and a Google search after the part names shows mostly boards that would have to be connected to existing circuits.

**Comment by mattsaxon** [comment]
Actually there isn't a picture, I'll have to rethink the best way to do it for you.

**Comment by mattsaxon** [comment]
Yep, I've realised this is non trivial. I opened my case and wired it into the terminals. You can do it externally, but need to make up a cable to do this and the terminal is not easy to find.

**Comment by mattsaxon** [comment]
If you are happy to open up your case and connect stuff to the board, just in existing terminals, no soldering required, then Im happy to try to get it to work with you.

Id suggest you go for the USR-TCP232-306 or USR-TCP232-304 device. This will require connection to the A and B terminals inside the case. I don't think anything else will be required apart from 2 wires to connect them. The terminals on both ends are screws.

Tell me if you are game and I'll think a bit harder

**Comment by raducotescu** [comment]
USR-TCP232-304 looks friendlier for some reason. How would the HA integration be configured in this case, given that you cannot point it to a `hidraw` device?

**Comment by mattsaxon** [comment]
304 is simpler. Uses external power supply. 306 can he powered off the control panel board.

Yes the connect string is as you say and you connect over Ethernet. There are some wifi compatible devices from the same company if you need.

**Comment by raducotescu** [comment]
Let’s close this. Probably the only reliable way to use the integration on Synology is with one of the hardware additions that @mattsaxon recommended.

I have explored compiling `hidraw` for Synology, but that’s a dead end due to the fact that the module is in-tree. Recompiling the whole kernel is too complicated and would need to be redone every time Synology pushes an update.

**Comment by neuhausf** [comment]
@mattsaxon I got a jablotron 80 and a USR-TCP232-304. In the wiki you write, that the USR can be powered directly from the control panel. Can you point me to the correct pins? Do you have a schema or picture?

**Comment by mattsaxon** [comment]
https://www.jablotron.com/en/about-jablotron/downloads/?filename=JA-80K_EN_MKE51801.pdf&do=downloadFile

+U and GND terminals, page 5

**Comment by neuhausf** [comment]
@mattsaxon Thx for the datasheet - I didn't find it.
Isn't +5 10 - 14V (normally 12V)? I guess the 304 should have 5V?
![image](https://user-images.githubusercontent.com/7963239/232073961-bf6394fe-5d07-468c-956b-533a3e2c8449.png)

**Comment by mattsaxon** [comment]
I don't recall exact specs, but you can either use a device that accepts that voltage (some of the TCP devices do) or use a small transformer. I have a small transformer which mounts inside the control panel also. I thought I specified this on the same page, but don't have it to hand now.

**Comment by mattsaxon** [comment]
Having looked at the specs, I would have expected the 304 to be easier to use its own power supply as the device only has terminals for RS485 that can connect to the control panel board directly, but power doesn't have bare terminals.

I'm sure you can set something up with the 304 though if you really want to avoid another power supply.

It's the 306 that has bare power terminals and also takes power in 5-36v range.

**Comment by neuhausf** [comment]
Thanks - that confirms my suspicions. I was now able to get the integration working with a 304 via the external power supply. But have ordered another 306, so the installation will be cleaner.

**Comment by neuhausf** [comment]
Quick follow up: I can confirm, that the mounting with a USR-TCP232-306 is the cleanest possible solution. It can be powered directly from U+/GND.
The case is a bit big - make sure you insulate the metal parts properly.

**Comment by mattsaxon** [comment]
So you've fitted it inside the control panel box? What's the reason you didn't elect from the usr-tcp232-t2?

**Comment by neuhausf** [comment]
Powersupply (only up to 5V allowed) and wiring (I am a bit lazy). The 306 is basically plug and play.

**Comment by neuhausf** [comment]
It's not the most beautiful installation in the world, but it works.
![IMG_1230](https://user-images.githubusercontent.com/7963239/235987733-89d4ee9c-c41c-4e4d-85f4-cf5e9f7e5fde.jpg)

**Comment by mattsaxon** [comment]
It's more compact than mine, since mine has 3 components in the case.

Good stuff

**Comment by PasekJ** [comment]
I have HA on Raspberry and I don't know how to set up communication "socket://[ipaddress:socket]", unfortunately I couldn't find anything here. I will be grateful for any direction. Thanks

**Comment by ondrejmirtes** [comment]
Thank you very much for this project! I used the README and this thread to successfully get this working!

* I bought this "serial to Wi-Fi" adapter: https://www.pusr.com/products/rs232-rs485-to-wifi-converters-usr-w610.html
* I connected "U+" on the board to "+", "GND" on the board to "-"
* I connected "A" to "A" and "B" to "B"
* I set up the W610 device using web UI and connected it to my Wi-Fi
* The integration in Home Assistant works flawlessly on the first try
* Additionally, I installed "HW VSP3 - Virtual Serial Port" software on my Windows PC and downloaded O-Link from Jablotron and now I can also configure the alarm remotely from my PC :)
