### ISSUE TITLE
Add support for triggering the alarm via the alarm_trigger service

### ISSUE THREAD

**Issue by raducotescu** [tahvane1/jablotron80#140]
I have successfully installed the integration to test its features and one thing I didn’t see is a way to trigger the siren. Can this be achieved on these systems or is the siren fully controlled by the alarm’s control panel, without any access to it from the serial port?

This would allow reusing the alarm’s devices but extend them with other sensors into an alarm system controlled by Home Assistant.

**Comment by tahvane1** [comment]
Intergration doesn't support it (for now), but if it is possible to trigger siren from control panel then I believe it could be done via integration as well.

**Comment by mattsaxon** [comment]
I achieve something similar with the addition of a custom physical sensor that is actually a smart switch. I then control this via Home Assistant

**Comment by raducotescu** [comment]
I actually found a way to do this using the panic alarm. PR coming soon.
