### ISSUE TITLE
No data flows with this integration without "initialisation message" being first sent

### ISSUE THREAD

**Issue by mattsaxon** [tahvane1/jablotron80#16]
My integration sends a startup message to trigger this to work.

It's only needed once per device reboot, so I only noticed it when I restarted my PI, not on restarts of HA.

Does no one else have this problem?

At the moment I've got my component installed side by side with this one to solve the problem, but I will add this startup message into this integration via a PR in due course, but before I do, I'm wondering why only I seem to have this problem.

```    def _startup_message(self):
        """ Send Start Message to panel"""

        _LOGGER.debug('Sending startup message')
        self._send_packet(b'\x00\x00\x01\x01')
        _LOGGER.debug('Successfully sent startup message')
```

is called from `__init__()` of `JablotronAlarm`

**Comment by tahvane1** [comment]
This is probably related to #7

**Comment by mattsaxon** [comment]
@tahvane1 would you like to close this message or leave it open pending #7
