### ISSUE TITLE
Deprecation messages after upgrading to 2024.1

### ISSUE THREAD

**Issue by JohnnyM84** [tahvane1/jablotron80#161]
Get the following deprivation messages after the upgrade of ha to 2024.1:

DEVICE_CLASS_SIGNAL_STRENGTH was used from jablotron80, this is a deprecated constant which will be removed in HA Core 2025.1. Use SensorDeviceClass.SIGNAL_STRENGTH instead, please create a bug report at https://github.com/tahvane1/jablotron80/issues
DEVICE_CLASS_SAFETY was used from jablotron80, this is a deprecated constant which will be removed in HA Core 2025.1. Use BinarySensorDeviceClass.SAFETY instead, please create a bug report at https://github.com/tahvane1/jablotron80/issues
DEVICE_CLASS_SMOKE was used from jablotron80, this is a deprecated constant which will be removed in HA Core 2025.1. Use BinarySensorDeviceClass.SMOKE instead, please create a bug report at https://github.com/tahvane1/jablotron80/issues
DEVICE_CLASS_WINDOW was used from jablotron80, this is a deprecated constant which will be removed in HA Core 2025.1. Use BinarySensorDeviceClass.WINDOW instead, please create a bug report at https://github.com/tahvane1/jablotron80/issues
DEVICE_CLASS_LIGHT was used from jablotron80, this is a deprecated constant which will be removed in HA Core 2025.1. Use BinarySensorDeviceClass.LIGHT instead, please create a bug report at https://github.com/tahvane1/jablotron80/issues
DEVICE_CLASS_POWER was used from jablotron80, this is a deprecated constant which will be removed in HA Core 2025.1. Use BinarySensorDeviceClass.POWER instead, please create a bug report at https://github.com/tahvane1/jablotron80/issues
FORMAT_NUMBER was used from jablotron80, this is a deprecated constant which will be removed in HA Core 2025.1. Use CodeFormat.NUMBER instead, please create a bug report at https://github.com/tahvane1/jablotron80/issues
SUPPORT_ALARM_ARM_HOME was used from jablotron80, this is a deprecated constant which will be removed in HA Core 2025.1. Use AlarmControlPanelEntityFeature.ARM_HOME instead, please create a bug report at https://github.com/tahvane1/jablotron80/issues
SUPPORT_ALARM_ARM_AWAY was used from jablotron80, this is a deprecated constant which will be removed in HA Core 2025.1. Use AlarmControlPanelEntityFeature.ARM_AWAY instead, please create a bug report at https://github.com/tahvane1/jablotron80/issues
SUPPORT_ALARM_ARM_NIGHT was used from jablotron80, this is a deprecated constant which will be removed in HA Core 2025.1. Use AlarmControlPanelEntityFeature.ARM_NIGHT instead, please create a bug report at https://github.com/tahvane1/jablotron80/issues
SUPPORT_ALARM_TRIGGER was used from jablotron80, this is a deprecated constant which will be removed in HA Core 2025.1. Use AlarmControlPanelEntityFeature.TRIGGER instead, please create a bug report at https://github.com/tahvane1/jablotron80/issues

**Comment by tahvane1** [comment]
Thank you for informing me. Will be fixed soon.
