### ISSUE TITLE
Request modify documentation: Remote Usage via USBIP 

### ISSUE THREAD

**Issue by sincze** [tahvane1/jablotron80#172]
Gave it already a shot here:

https://community.home-assistant.io/t/jablotron-ja-80-series-and-ja-100-series-alarm-integration/113315/495

Plugin will also work via LAN where there is a remote homeassistant (CLIENT) and a SERVER with the JA USB cable serving /dev/hidraw0.

**Comment by tahvane1** [comment]
It would be great if you could create PR for documentation update...

**Comment by sincze** [comment]
> It would be great if you could create PR for documentation update...

Let me do that for you. No Problem.

**Comment by sincze** [comment]
Pull Request has been Created
