### ISSUE TITLE
Dashboard code example doesn't work

### ISSUE THREAD

**Issue by mattsaxon** [tahvane1/jablotron80#40]
The dashboard code needs custom components (card-mod) and also defined items such as spacers.

Please can the example/docs be improved so I can get the dashboard working

**Comment by mattsaxon** [comment]
Thanks, that works a treat.

@tahvane1 what's your preference here? Shall we correct your documentation (for how to configure card-mod) or use the one above from @JohnnyM84 (which uses the custom button card).

**Comment by FraBoCH** [comment]
What's the advantage of using the custom button card ? I'm using the simple out of the box "button" and it works great as well. 
IMHO, the documentation should show a configuration that could be copy pasted as is by everybody.

**Comment by mattsaxon** [comment]
@FraBoCH can you paste your config?

**Comment by tahvane1** [comment]
I don't think that it makes sense to reproduce a lot of documentation already available online. Maybe just mention that HA standard alarm control panel is used and link to that (I guess this one https://www.home-assistant.io/lovelace/alarm-panel/)?

**Comment by tahvane1** [comment]
We can also add Johnny's config as another example if that is okay with  @JohnnyM84

**Comment by JohnnyM84** [comment]
Yes that’s oké

**Comment by mattsaxon** [comment]
Whilst we can reference examples, I wonder if it would be useful for less technically minded people to have a basic dashboard that integrates the non standard sensors. One that is as simple as possible and uses the minimum custom. I think that is what @JohnnyM84 may be offering up

**Comment by mattsaxon** [comment]
@FraBoCH do you have a config that you are proposing as the simplest example that doesn't need any custom extensions?

**Comment by JohnnyM84** [comment]
If you change custom:button-card to button than it works without a custom card, but the colors of the zones are the default colors of your theme in home Assistant

**Comment by FraBoCH** [comment]
I've created pull request #75 with a proposition of readme update.
