### ISSUE TITLE
Error adding integration

### ISSUE THREAD

**Issue by tinus20vt** [tahvane1/jablotron80#6]
Hi Erkka,

I've closed the old issue, we couldn't get it working with a JA-80T.
So, i bought a JA-82T and i was hoping that this work instantly........

I get an error when add the integration with the following parameters:
![image](https://user-images.githubusercontent.com/35401875/111463983-80878380-8720-11eb-9e80-2c99ba3ffe37.png)

I've added the settings below:
![image](https://user-images.githubusercontent.com/35401875/111467809-2a690f00-8725-11eb-8e37-2287820a9870.png)

![image](https://user-images.githubusercontent.com/35401875/111468330-b713cd00-8725-11eb-81aa-68e20e2f1121.png)

This gives the error below:
![image](https://user-images.githubusercontent.com/35401875/111467859-38b72b00-8725-11eb-8910-cf53359a3af0.png)

The log in HA:
![image](https://user-images.githubusercontent.com/35401875/111467911-47054700-8725-11eb-8c01-cfc2614e85cf.png)

And the extensive logging:
![image](https://user-images.githubusercontent.com/35401875/111468021-67350600-8725-11eb-97a6-af48edc26c9f.png)

Do you have any idea?

**Comment by tahvane1** [comment]
Hi,
most probably wrong device. Do you have /dev/hidraw0 or something like that? It should be HID interface (as far as I know)... 
Br,
Erkka

**Comment by tinus20vt** [comment]
I thought also. 
When i check my hardware I've:
/dev/usb/hiddev0
/dev/hidraw1
/dev/hidraw0

None of them works and gives the same error.
It is strange that the address from the JA-82 is "DEVNAME: /dev/bus/usb/002/002" never seen before.
I just checked if the JA-82T works but with Olink it just works.

**Comment by tinus20vt** [comment]
It is hidraw1:
![image](https://user-images.githubusercontent.com/35401875/111488878-f21ffb80-8739-11eb-9e26-3532a56798c8.png)

But the result:
![image](https://user-images.githubusercontent.com/35401875/111488944-ffd58100-8739-11eb-8288-28e4f561cfb5.png)

**Comment by tinus20vt** [comment]
I don't know what happen, first it didn't work. 
So tried the integration from mattsaxon and that works. After that, i tried again with your integration and set the same credentials as before and now it works.

Thanks for all the effort.
